# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  batch: true
  branches:
    include:
    - master

pr: none

jobs:
- job: build
  timeoutInMinutes: 60

  pool:
    vmImage: 'Ubuntu-latest'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - script: |
      go version
      go get -v -t -d ./...
      make deps
      if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
      fi
      sudo apt-get install gcc g++ python2.7 python3
      
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies'
  - script: |
      make build-linux64
    workingDirectory: '$(modulePath)'
    displayName: 'Build for Linux 64'
  - script: |
      make build-linux32
    workingDirectory: '$(modulePath)'
    displayName: 'Build for Linux 32'